
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lib-app_development

test:
  <<: *default
  database: lib-app_test

production:
  <<: *default
  database: lib-app_production
  username: lib-app
  password: <%= ENV['LIB-APP_DATABASE_PASSWORD'] %>
